### ISSUE TITLE
No '+' or '-' in fasta files

### ISSUE THREAD

**Issue by nityanandagohain** [BugHoppers/GENE-checker#2]
Should we consider the "FORWARD" /"REVERSED" keyword. I don't see any '+' or '-' signs. @AdirthaBorgohain

**Comment by AdirthaBorgohain** [comment]
I'll go through the fasta files and let you know.

**Comment by AdirthaBorgohain** [comment]
As far as I could understand, we need to go through the term "FORWARD" or "REVERSE". FORWARD equates + while REVERSE equates -. Should be it.

**Comment by nityanandagohain** [comment]
Great, I have have separated the genes according to that in the code. Just need to do the inverse thing.
